project_id = "xzlhssqqbajqhnsmbucf"

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.get-certificate-url]
verify_jwt = true

[functions.hide-cms-element]
verify_jwt = true

[functions.save-cms-layout]
verify_jwt = true

[functions.send-group-email]
verify_jwt = true

[functions.send-training-notification]
verify_jwt = true

[functions.generate-certificate-background]
verify_jwt = true

[functions.auto-generate-certificate]
verify_jwt = true

[functions.support-chat]
verify_jwt = false

[functions.medical-assistant]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.download-resource]
verify_jwt = false

[functions.ai-compass]
verify_jwt = true

[functions.generate-daily-signal]
verify_jwt = true

[functions.background-translate]
verify_jwt = false
